# copied from https://jupyterbook.org/publish/gh-pages.html?highlight=github%20pages

name: test-build

# Only run this when a PR suggests changes to main branch
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

# This job installs dependencies and builds the book
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: environment.yml
        activate-environment: arcdocs-jb

    # Build the book
    - name: Build the book
      shell: bash -l {0}
      run: |
        conda activate arcdocs-jb
        jupyter-book build ./book/
